# -*- coding: utf-8 -*-
"""PMO_Agent_System_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URqy8ktdrBNI4nd0d9_j0X73bOWol5ey

# PMO Agent System
**CR Agent · Plan Agent · RAID Agent**

Run each cell in order. All agents run directly in Python — no localhost or browser fetch issues.
"""

# Cell 1 — Install dependencies (Switched to Google Generative AI)
!pip install -q -U google-generativeai
print('Done.')

# ── Nuclear clean — strips everything GitHub chokes on ─────
import json

notebook_path = '/content/drive/My Drive/Colab Notebooks/PMO_Agent_System_Colab.ipynb'

with open(notebook_path, 'r') as f:
    nb = json.load(f)

# 1. Remove widgets from top-level metadata
nb['metadata'].pop('widgets', None)

# 2. Clean every cell
for cell in nb.get('cells', []):

    # Clear ALL outputs entirely — removes all widget state
    cell['outputs'] = []
    cell['execution_count'] = None

    # Remove widget state from cell metadata
    cell.get('metadata', {}).pop('widgets', None)

# 3. Force correct nbformat
nb['nbformat'] = 4
nb['nbformat_minor'] = 5

# Save
with open('/content/drive/My Drive/Colab Notebooks/PMO_Agent_System_Colab.ipynb', 'w') as f:
    json.dump(nb, f, indent=2)

print('Done — download PMO_Agent_System_Colab.ipynb')

from google.colab import drive
drive.mount('/content/drive')

# Cell 2 — Set Google Gemini API key
import os
import google.generativeai as genai

try:
    from google.colab import userdata
    os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')
    print('✅ API key loaded from Colab Secrets.')
except Exception:
    os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')
    print('⚠️ API key set directly.')

genai.configure(api_key=os.environ['GOOGLE_API_KEY'])
print('Gemini Client Configured.')

# Cell 3 — Core agent logic (Updated for Gemini 1.5 Flash)
import os, json, csv, io
import google.generativeai as genai
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets

stored_csvs = {}

SYSTEM_PROMPTS = {
    'cr': "You are a PMO Change Request Agent. Compare a meeting transcript against a signed SOW and identify change requests. Return ONLY a valid JSON array of objects with keys: cr_id, date_raised, project_name, title, description, source, requested_by, scope_baseline_ref, impact_scope, priority, estimated_effort, cost_impact, status, owner, resolution_date, notes.",
    'plan': "You are a PMO Project Plan Agent. Extract a structured project plan (WBS). Return ONLY a valid JSON array of objects with keys: task_id, phase, task_name, description, owner, team, start_date, end_date, duration_days, dependencies, milestone, status, completion_pct, priority, notes, smartsheet_row_id.",
    'raid': "You are a PMO RAID Log Agent. Analyse context and produce a RAID log. Return ONLY a valid JSON array of objects with keys: raid_id, type, date_raised, title, description, source, raised_by, owner, probability, impact, risk_score, mitigation_action, contingency, status, target_date, resolution_notes."
}

def call_gemini(agent, user_msg):
    # Using Gemini 1.5 Flash - High speed and generous free tier
    model = genai.GenerativeModel(
        model_name="gemini-2.5-flash", # <--- Updated this line
        system_instruction=SYSTEM_PROMPTS[agent]
    )

    response = model.generate_content(user_msg)
    raw = response.text.strip()

    # Clean JSON markdown if the model includes it
    clean = raw.replace('```json', '').replace('```', '').strip()
    return json.loads(clean)

# (Keeping your original helper functions for rendering)
BADGE_COLORS = {'High': ('#FCEBEB','#791F1F'), 'Red': ('#FCEBEB','#791F1F'), 'Medium': ('#FAEEDA','#633806'), 'Low': ('#EAF3DE','#27500A'), 'Green': ('#EAF3DE','#27500A'), 'Risk': ('#FAECE7','#712B13'), 'Issue': ('#FCEBEB','#791F1F'), 'Dependency': ('#E6F1FB','#0C447C')}
BADGE_COLS = {'status','type','priority','impact','probability','risk_score','impact_scope','milestone'}

def badge(val):
    if val in BADGE_COLORS:
        bg, fg = BADGE_COLORS[val]
        return f'<span style="background:{bg};color:{fg};font-size:11px;font-weight:500;padding:2px 8px;border-radius:99px;">{val}</span>'
    return val

def render_table(rows):
    if not rows: return '<p>No results.</p>'
    cols = list(rows[0].keys())
    th = ''.join(f'<th style="background:#f5f5f3;padding:7px;font-size:11px;border-bottom:1px solid #ddd;">{c.replace("_"," ")}</th>' for c in cols)
    body = ''
    for r in rows:
        cells = ''.join(f'<td style="padding:7px;border-bottom:1px solid #eee;font-size:12px;">{badge(str(r.get(c,""))) if c in BADGE_COLS else str(r.get(c,""))}</td>' for c in cols)
        body += f'<tr>{cells}</tr>'
    return f'<table style="width:100%;border-collapse:collapse;"><thead>{th}</thead><tbody>{body}</tbody></table>'

def render_metrics(agent, rows):
    count = len(rows)
    return f'<div style="background:#f5f5f3;padding:10px;border-radius:8px;margin-bottom:10px;"><b>Total Items Generated:</b> {count}</div>'

def rows_to_csv(rows):
    if not rows: return ''
    out = io.StringIO()
    w = csv.DictWriter(out, fieldnames=rows[0].keys())
    w.writeheader()
    w.writerows(rows)
    return out.getvalue()

print('✅ Gemini Agent logic loaded.')

import google.generativeai as genai
for m in genai.list_models():
    if 'generateContent' in m.supported_generation_methods:
        print(f"✅ Use this string: {m.name}")

# ── CELL 4: PMO Agent UI (ipywidgets — no localhost fetch) ─────────────────────
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# ── Shared style ──
TA_STYLE  = {'width': '100%'}
TA_LAYOUT = widgets.Layout(width='100%', height='120px')
IN_LAYOUT = widgets.Layout(width='100%', height='34px')

def styled_label(text):
    return widgets.HTML(f'<div style="font-size:12px;font-weight:600;color:#5a5a56;margin-bottom:4px;">{text}</div>')

def section_title(text, sub=''):
    s = f'<div style="font-size:16px;font-weight:600;margin-bottom:2px;">{text}</div>'
    if sub:
        s += f'<div style="font-size:12px;color:#5a5a56;margin-bottom:12px;">{sub}</div>'
    return widgets.HTML(s)

# ────────────────────────────────────────────────────────────
# CR AGENT TAB
# ────────────────────────────────────────────────────────────
cr_title      = section_title('CR Agent', 'Paste a meeting transcript and SOW to generate a change request log.')
cr_transcript = widgets.Textarea(placeholder='Paste meeting transcript or kickoff notes here...', layout=TA_LAYOUT)
cr_sow        = widgets.Textarea(placeholder='Paste relevant SOW sections here...', layout=TA_LAYOUT)
cr_project    = widgets.Text(placeholder='e.g. Acme Bank Digital Onboarding', layout=IN_LAYOUT)
cr_priority   = widgets.Dropdown(options=['High','Medium','Low'], value='Medium',
                                  layout=widgets.Layout(width='100%'))
cr_run_btn    = widgets.Button(description='▶  Run CR Agent',
                                button_style='', icon='',
                                layout=widgets.Layout(width='180px', height='38px'),
                                style={'button_color':'#1a1a18','font_weight':'600'})
cr_dl_btn     = widgets.Button(description='↓  Download CSV',
                                layout=widgets.Layout(width='180px', height='38px', display='none'),
                                style={'button_color':'#f5f5f3'})
cr_status     = widgets.Output()
cr_results    = widgets.Output()

cr_left  = widgets.VBox([styled_label('Meeting transcript / notes'), cr_transcript],
                         layout=widgets.Layout(width='50%', padding='0 6px 0 0'))
cr_right = widgets.VBox([styled_label('SOW / scope document'), cr_sow],
                         layout=widgets.Layout(width='50%', padding='0 0 0 6px'))
cr_pl    = widgets.VBox([styled_label('Project name'), cr_project],
                         layout=widgets.Layout(width='50%', padding='0 6px 0 0'))
cr_pr    = widgets.VBox([styled_label('Default priority'), cr_priority],
                         layout=widgets.Layout(width='50%', padding='0 0 0 6px'))



def on_cr_run(b):
    transcript = cr_transcript.value.strip()
    sow        = cr_sow.value.strip()
    project    = cr_project.value.strip() or 'Project'
    priority   = cr_priority.value

    cr_status.clear_output()
    cr_results.clear_output()

    if not transcript or not sow:
        with cr_status:
            display(HTML('<div style="background:#FCEBEB;color:#791F1F;padding:10px 14px;border-radius:8px;font-size:13px;">'
                         '✗ Please fill in both the transcript and SOW fields.</div>'))
        return

    cr_run_btn.disabled    = True
    cr_run_btn.description = '⏳ Running...'

    with cr_status:
        display(HTML('<div style="background:#EEF4FF;color:#1a4fb5;padding:10px 14px;border-radius:8px;'
                     'font-size:13px;display:flex;align-items:center;gap:8px;">'
                     '<b>Gemini Agent is running</b> — comparing transcript vs SOW...</div>'))

    try:
        user_msg = (f'PROJECT: {project}\nDEFAULT PRIORITY: {priority}\n\n'
                    f'MEETING TRANSCRIPT:\n{transcript}\n\nSOW / SCOPE DOCUMENT:\n{sow}')

        # --- CHANGED FROM call_claude TO call_gemini ---
        rows = call_gemini('cr', user_msg)
        stored_csvs['cr'] = rows

        oos   = sum(1 for r in rows if r.get('impact_scope') == 'Out of Scope')
        extra = f' — {oos} out-of-scope item{"s" if oos != 1 else ""}' if oos else ''

        cr_status.clear_output()
        with cr_status:
            display(HTML(f'<div style="background:#E1F5EE;color:#085041;padding:10px 14px;border-radius:8px;font-size:13px;">'
                         f'✓ Done. Generated {len(rows)} change request{"s" if len(rows)!=1 else ""}{extra}.</div>'))
        with cr_results:
            display(HTML(render_metrics('cr', rows) + render_table(rows)))
        cr_dl_btn.layout.display = ''

    except Exception as e:
        cr_status.clear_output()
        with cr_status:
            display(HTML(f'<div style="background:#FCEBEB;color:#791F1F;padding:10px 14px;border-radius:8px;font-size:13px;">'
                         f'✗ Error: {str(e)}</div>'))
    finally:
        cr_run_btn.disabled    = False
        cr_run_btn.description = '▶  Run CR Agent'

def on_cr_dl(b):
    rows = stored_csvs.get('cr')
    if not rows: return
    csv_str = rows_to_csv(rows)
    with cr_results:
        display(HTML(
            f'<div style="margin-top:10px;padding:10px 14px;background:#f5f5f3;border-radius:8px;font-size:12px;">'
            f'<b>CSV preview (copy and save as change_requests.csv):</b><br><br>'
            f'<textarea style="width:100%;height:180px;font-size:11px;font-family:monospace;'
            f'border:1px solid #ddd;border-radius:4px;padding:8px;">{csv_str}</textarea></div>'
        ))

cr_run_btn.on_click(on_cr_run)
cr_dl_btn.on_click(on_cr_dl)

cr_tab = widgets.VBox([
    cr_title,
    widgets.HBox([cr_left, cr_right]),
    widgets.HBox([cr_pl, cr_pr], layout=widgets.Layout(margin='8px 0')),
    widgets.HBox([cr_run_btn, cr_dl_btn], layout=widgets.Layout(gap='10px')),
    cr_status,
    cr_results,
], layout=widgets.Layout(padding='16px'))

# ────────────────────────────────────────────────────────────
# PLAN AGENT TAB
# ────────────────────────────────────────────────────────────
plan_title  = section_title('Plan Agent', 'Provide kickoff notes and email context to build a full project plan.')
plan_notes  = widgets.Textarea(placeholder='Paste kickoff notes and SOW deliverables...', layout=TA_LAYOUT)
plan_email  = widgets.Textarea(placeholder='Paste relevant email threads...', layout=TA_LAYOUT)
plan_run_btn= widgets.Button(description='▶  Run Plan Agent',
                              layout=widgets.Layout(width='190px', height='38px'),
                              style={'button_color':'#1a1a18','font_weight':'600'})
plan_dl_btn = widgets.Button(description='↓  Download CSV',
                              layout=widgets.Layout(width='180px', height='38px', display='none'),
                              style={'button_color':'#f5f5f3'})
plan_status = widgets.Output()
plan_results= widgets.Output()

plan_left  = widgets.VBox([styled_label('Kickoff notes + scope'), plan_notes],
                           layout=widgets.Layout(width='50%', padding='0 6px 0 0'))
plan_right = widgets.VBox([styled_label('Email threads / context'), plan_email],
                           layout=widgets.Layout(width='50%', padding='0 0 0 6px'))



def on_plan_run(b):
    notes = plan_notes.value.strip()
    email = plan_email.value.strip()
    plan_status.clear_output()
    plan_results.clear_output()

    if not notes:
        with plan_status:
            display(HTML('<div style="background:#FCEBEB;color:#791F1F;padding:10px 14px;border-radius:8px;font-size:13px;">✗ Please provide kickoff notes.</div>'))
        return

    plan_run_btn.disabled = True
    plan_run_btn.description = '⏳ Running...'

    try:
        user_msg = f'KICKOFF NOTES:\\n{notes}\\n\\nEMAIL CONTEXT:\\n{email or "None provided."}'
        rows = call_gemini('plan', user_msg) # --- CHANGED ---
        stored_csvs['plan'] = rows
        plan_status.clear_output()
        with plan_results:
            display(HTML(render_metrics('plan', rows) + render_table(rows)))
        plan_dl_btn.layout.display = ''
    except Exception as e:
        with plan_status: display(HTML(f'✗ Error: {str(e)}'))
    finally:
        plan_run_btn.disabled = False
        plan_run_btn.description = '▶  Run Plan Agent'

def on_plan_dl(b):
    rows = stored_csvs.get('plan')
    if not rows: return
    csv_str = rows_to_csv(rows)
    with plan_results:
        display(HTML(f'<div style="margin-top:10px;padding:10px 14px;background:#f5f5f3;border-radius:8px;font-size:12px;">'
                     f'<b>CSV preview (copy and save as project_plan.csv):</b><br><br>'
                     f'<textarea style="width:100%;height:180px;font-size:11px;font-family:monospace;border:1px solid #ddd;border-radius:4px;padding:8px;">{csv_str}</textarea></div>'))

plan_run_btn.on_click(on_plan_run)
plan_dl_btn.on_click(on_plan_dl)

plan_tab = widgets.VBox([
    plan_title,
    widgets.HBox([plan_left, plan_right]),
    widgets.HBox([plan_run_btn, plan_dl_btn], layout=widgets.Layout(margin='8px 0', gap='10px')),
    plan_status, plan_results,
], layout=widgets.Layout(padding='16px'))

# ────────────────────────────────────────────────────────────
# RAID AGENT TAB
# ────────────────────────────────────────────────────────────
raid_title   = section_title('RAID Agent', 'Paste all project context to generate a RAID log with risk scores and mitigations.')
raid_input   = widgets.Textarea(placeholder='Paste all project context here...', layout=TA_LAYOUT)
raid_risks   = widgets.Textarea(placeholder='Any explicitly stated risks or blockers...', layout=TA_LAYOUT)
raid_run_btn = widgets.Button(description='▶  Run RAID Agent',
                               layout=widgets.Layout(width='190px', height='38px'),
                               style={'button_color':'#1a1a18','font_weight':'600'})
raid_dl_btn  = widgets.Button(description='↓  Download CSV',
                               layout=widgets.Layout(width='180px', height='38px', display='none'),
                               style={'button_color':'#f5f5f3'})
raid_status  = widgets.Output()
raid_results = widgets.Output()

raid_left  = widgets.VBox([styled_label('Project context (transcript, notes, emails)'), raid_input],
                           layout=widgets.Layout(width='50%', padding='0 6px 0 0'))
raid_right = widgets.VBox([styled_label('Known risks / blockers'), raid_risks],
                           layout=widgets.Layout(width='50%', padding='0 0 0 6px'))



def on_raid_run(b):
    inp = raid_input.value.strip()
    rsk = raid_risks.value.strip()
    raid_status.clear_output()
    raid_results.clear_output()

    if not inp:
        with raid_status: display(HTML('✗ Please provide context.'))
        return

    raid_run_btn.disabled = True
    try:
        user_msg = f'CONTEXT:\\n{inp}\\n\\nRISKS:\\n{rsk or "None."}'
        rows = call_gemini('raid', user_msg) # --- CHANGED ---
        stored_csvs['raid'] = rows
        with raid_results:
            display(HTML(render_metrics('raid', rows) + render_table(rows)))
        raid_dl_btn.layout.display = ''
    except Exception as e:
        with raid_status: display(HTML(f'✗ Error: {str(e)}'))
    finally:
        raid_run_btn.disabled = False

def on_raid_dl(b):
    rows = stored_csvs.get('raid')
    if not rows: return
    csv_str = rows_to_csv(rows)
    with raid_results:
        display(HTML(f'<div style="margin-top:10px;padding:10px 14px;background:#f5f5f3;border-radius:8px;font-size:12px;">'
                     f'<b>CSV preview (copy and save as raid_log.csv):</b><br><br>'
                     f'<textarea style="width:100%;height:180px;font-size:11px;font-family:monospace;border:1px solid #ddd;border-radius:4px;padding:8px;">{csv_str}</textarea></div>'))

raid_run_btn.on_click(on_raid_run)
raid_dl_btn.on_click(on_raid_dl)

raid_tab = widgets.VBox([
    raid_title,
    widgets.HBox([raid_left, raid_right]),
    widgets.HBox([raid_run_btn, raid_dl_btn], layout=widgets.Layout(margin='8px 0', gap='10px')),
    raid_status, raid_results,
], layout=widgets.Layout(padding='16px'))

# ────────────────────────────────────────────────────────────
# ASSEMBLE TABS
# ────────────────────────────────────────────────────────────
tab = widgets.Tab(children=[cr_tab, plan_tab, raid_tab])
tab.set_title(0, 'CR Agent')
tab.set_title(1, 'Plan Agent')
tab.set_title(2, 'RAID Agent')

header = widgets.HTML(
    '<div style="font-family:sans-serif;background:#fff;border:1px solid #e0dfd9;'
    'border-radius:10px 10px 0 0;padding:14px 20px;border-bottom:none;">'
    '<div style="font-size:16px;font-weight:700;">PMO Agent System</div>'
    '<div style="font-size:12px;color:#8a8a85;margin-top:2px;">'
    'Powered by Claude &middot; CR Agent &middot; Plan Agent &middot; RAID Agent</div></div>'
)

display(widgets.VBox([header, tab]))

# ── CELL 5: Append CSVs to Google Drive (Project Memory) ──────────────────────
import csv, os
from datetime import datetime
from google.colab import drive

# ── Step 1: Mount Google Drive ──
drive.mount('/content/drive', force_remount=False)

# ── Step 2: Set your project folder path ──
PROJECT_NAME = 'Acme_Bank_Digital_Onboarding'   # ← keep same name across sessions
DRIVE_FOLDER = f'/content/drive/My Drive/PMO_Agent/{PROJECT_NAME}'
os.makedirs(DRIVE_FOLDER, exist_ok=True)

# ── Step 3: Session metadata ──
session_date = datetime.now().strftime('%Y-%m-%d')
session_ts   = datetime.now().strftime('%Y-%m-%d %H:%M')

FILE_MAP = {
    'cr'  : 'change_requests.csv',
    'plan': 'project_plan.csv',
    'raid': 'raid_log.csv',
}

appended = []
skipped  = []

for agent, filename in FILE_MAP.items():
    new_rows = stored_csvs.get(agent)
    if not new_rows:
        skipped.append(filename)
        continue

    filepath = os.path.join(DRIVE_FOLDER, filename)

    # ── Tag each new row with session date so you know which run it came from ──
    for row in new_rows:
        row['session_date'] = session_date

    if os.path.exists(filepath):
        # ── File exists — read existing rows, find duplicates, append only new ──
        with open(filepath, 'r', newline='') as f:
            reader     = csv.DictReader(f)
            existing   = list(reader)
            all_fields = reader.fieldnames or []

        # Add session_date column if it wasn't there before
        if 'session_date' not in all_fields:
            all_fields = all_fields + ['session_date']

        # Add any new columns from this run that didn't exist before
        for row in new_rows:
            for key in row.keys():
                if key not in all_fields:
                    all_fields.append(key)

        # Determine ID column per agent to detect duplicates
        id_col = {'cr': 'cr_id', 'plan': 'task_id', 'raid': 'raid_id'}.get(agent)

        existing_ids = set(r.get(id_col, '') for r in existing) if id_col else set()

        # Separate truly new rows from duplicates
        rows_to_add = []
        duplicates  = 0
        for row in new_rows:
            row_id = row.get(id_col, '')
            if id_col and row_id in existing_ids:
                duplicates += 1
            else:
                rows_to_add.append(row)

        # Write back: all existing rows + new unique rows
        all_rows = existing + rows_to_add
        with open(filepath, 'w', newline='') as f:
            w = csv.DictWriter(f, fieldnames=all_fields, extrasaction='ignore')
            w.writeheader()
            w.writerows(all_rows)

        appended.append({
            'file'      : filename,
            'added'     : len(rows_to_add),
            'duplicates': duplicates,
            'total'     : len(all_rows),
        })

    else:
        # ── File does not exist yet — create it fresh ──
        all_fields = list(new_rows[0].keys())
        with open(filepath, 'w', newline='') as f:
            w = csv.DictWriter(f, fieldnames=all_fields, extrasaction='ignore')
            w.writeheader()
            w.writerows(new_rows)

        appended.append({
            'file'      : filename,
            'added'     : len(new_rows),
            'duplicates': 0,
            'total'     : len(new_rows),
        })

# ── Step 4: Print summary ──
print('=' * 55)
print(f'  PMO Agent — Google Drive Sync (Append Mode)')
print(f'  Project : {PROJECT_NAME}')
print(f'  Folder  : My Drive/PMO_Agent/{PROJECT_NAME}')
print(f'  Run at  : {session_ts}')
print('=' * 55)

if appended:
    print('\n✓ Files updated:\n')
    for r in appended:
        print(f"   {r['file']}")
        print(f"     + {r['added']} new rows added")
        if r['duplicates']:
            print(f"     ~ {r['duplicates']} duplicate rows skipped")
        print(f"     = {r['total']} total rows in file")
        print()

if skipped:
    print(f"  Skipped (no data): {', '.join(skipped)}\n")

print('  Open drive.google.com to view your files.')
print(f'  Path: My Drive → PMO_Agent → {PROJECT_NAME}')